### ISSUE TITLE
Fatal error: Class 'GridFieldBulkUpload' not found

### ISSUE THREAD

**Issue by SqualaDesign** [purplespider/silverstripe-basic-galleries#10]
I installed your module but if I want create a new gallery I have this error

Fatal error: Class 'GridFieldBulkUpload' not found in /basic-galleries/code/PhotoGalleryExtension.php on line 14

**Comment by SqualaDesign** [comment]
I have also 
Fatal error: Class 'GridFieldGalleryTheme' not found in /basic-galleries/code/PhotoGalleryExtension.php on line 15

**Comment by purplespider** [comment]
Sounds like a couple of the required addons are missing from your install. Did you install using composer? As it should have installed these for you.
`composer require purplespider/basic-galleries`
